### ISSUE TITLE
Is that working for IOS push ??

### ISSUE THREAD

**Issue by tarikul05** [ker0x/cakephp-push#16]

**Comment by ker0x** [comment]
Hello @tarikul05 !

Firebase Cloud Messaging support iOS push, so my plugin also normally. However, I haven't been able to test it on an iOS device because I do not have one.

[Here](https://firebase.google.com/docs/cloud-messaging/http-server-ref) you can find some documentations about supported keys for iOS !

**Comment by tarikul05** [comment]
@ker0x got it, Thanks
